name: publish to nuget
on:
  push:
    branches:
      - release # Default release branch
      - preview/**
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build binaries
        run: dotnet build -c Release src/Cliargs/Cliargs.NET.csproj

      - name: Creating a package
        run: dotnet pack --no-build -c Release src/Cliargs/Cliargs.NET.csproj -o .

      - name: Publish to Nuget 
        run: dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.CLIARGS_NUGET}} --skip-duplicate -n 